# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,1
#monitor=HDMI-A-1,preferred,transform,auto

# Vertical monitor on the left (HDMI-A-1)
# The transform value of '1' rotates the display 90 degrees clockwise (to the right).
# Note the swapped dimensions (1080x1920) for the rotated screen.
monitor=HDMI-A-1, 1920x1080@60, 0x0, 1.25, transform, 1

# Primary landscape monitor in the center (DP-2)
# This monitor is placed directly to the right of the vertical one.
# Its position is at x=1080 to account for the width of the rotated monitor.
monitor=DP-2, 1920x1080@240, 864x228, 1
#monitor=DP-2,disable,1920x1080@240,864x228,1

# Secondary landscape monitor on the right (DP-3)
# This monitor is placed to the right of the center (DP-2) monitor.
# Its position is at x=3000 (1080 + 1920).
monitor=DP-3, 1920x1080@165, 2784x228, 1

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# monitor=,preferred,auto,1

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = "eDP-1, 2880x1920@120, auto, 3
#
#
